version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_admin"
      POSTGRES_PASSWORD: "test_password"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"